name: Build Backend

on:
  workflow_call:
  pull_request:
    branches: [develop, main]
    paths:
      - 'order-app/**'
      - 'pulumi/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Application
        run: mvn clean compile test package
        working-directory: order-app/

      - name: Build Pulumi Infrastructure
        run: mvn clean compile
        working-directory: pulumi/
